/**
 * S.E.E.D. — Buddy's World
 * BaseGameScene.ts
 *
 * Shared base class for all 4 module scenes. Handles:
 *   - Sky/hills background (textures generated by LoadScene)
 *   - 4-segment progress bar
 *   - Buddy avatar instantiation
 *   - Inactivity detection: Buddy "calls" at 10s, force-advance at 30s
 *     (recorded as a disengagement event)
 *   - Fade transitions between scenes
 *
 * Subclasses must implement:
 *   onCreate()    — module-specific setup (gameplay, trial sequencing)
 *   forceAdvance() — what to do when the child is unresponsive for 30s
 */

import Phaser from 'phaser'
import { BuddySprite } from '../utils/BuddySprite'
import { ProgressBar } from '../utils/ProgressBar'
import { SoundManager } from '../utils/SoundManager'
import { AgeAdapter } from '../utils/AgeAdapter'
import { EventCollector } from '../analytics/EventCollector'

export const CANVAS_WIDTH = 800
export const CANVAS_HEIGHT = 600

export abstract class BaseGameScene extends Phaser.Scene {
  protected buddy!: BuddySprite
  protected progressBar!: ProgressBar
  protected eventCollector!: EventCollector
  protected ageAdapter!: AgeAdapter
  protected soundManager!: SoundManager
  protected ageMonths!: number

  /** 0-3, set by each module subclass before create() runs (class field). */
  protected abstract moduleIndex: number
  /** matches module_id used in analysis engine event mapping */
  protected abstract moduleKey: string

  private inactivityCallTimer?: Phaser.Time.TimerEvent
  private inactivityAdvanceTimer?: Phaser.Time.TimerEvent
  private hasCalledForAttention = false
  private lastInteractionMs = 0
  private sceneActive = true

  create(): void {
    this.sceneActive = true

    this.eventCollector = this.game.registry.get('eventCollector') as EventCollector
    this.ageAdapter = this.game.registry.get('ageAdapter') as AgeAdapter
    this.soundManager = this.game.registry.get('soundManager') as SoundManager
    this.ageMonths = this.game.registry.get('ageMonths') as number

    this.addBackground()

    this.progressBar = new ProgressBar(this, 60, 24, CANVAS_WIDTH - 120, 4)
    this.progressBar.setActive(this.moduleIndex)

    this.buddy = new BuddySprite(this, CANVAS_WIDTH / 2, 470, 1)

    this.input.on('pointerdown', () => this.resetInactivityTimer())
    this.resetInactivityTimer()

    this.cameras.main.fadeIn(300, 224, 244, 255)

    this.onCreate()
  }

  /** Module-specific setup. Called at the end of create(). */
  protected abstract onCreate(): void

  /** Called when the child has been unresponsive for 30s. */
  protected abstract forceAdvance(): void

  // ── Background ──────────────────────────────────────────────────────────────

  protected addBackground(): void {
    this.add.image(CANVAS_WIDTH / 2, CANVAS_HEIGHT / 2, 'sky-bg').setDepth(-10)
    this.add.image(CANVAS_WIDTH / 2, CANVAS_HEIGHT - 75, 'hills').setDepth(-9)

    // Scattered clouds for ambience
    const cloudPositions: Array<[number, number]> = [[120, 90], [620, 70], [380, 130]]
    cloudPositions.forEach(([x, y]) => {
      this.add.image(x, y, 'cloud').setDepth(-8).setAlpha(0.9)
    })
  }

  // ── Inactivity handling ─────────────────────────────────────────────────────

  protected resetInactivityTimer(): void {
    this.lastInteractionMs = this.time.now
    this.hasCalledForAttention = false

    this.inactivityCallTimer?.remove()
    this.inactivityAdvanceTimer?.remove()

    const cfg = this.ageAdapter.getConfig()

    this.inactivityCallTimer = this.time.delayedCall(cfg.inactivityCallMs, () => {
      this.onInactivityCall()
    })

    this.inactivityAdvanceTimer = this.time.delayedCall(cfg.inactivityAdvanceMs, () => {
      this.onInactivityAdvance()
    })
  }

  protected onInactivityCall(): void {
    if (!this.sceneActive || this.hasCalledForAttention) return
    this.hasCalledForAttention = true
    this.soundManager.play('buddy_call')
    this.buddy.playCall()
  }

  protected onInactivityAdvance(): void {
    if (!this.sceneActive) return
    const elapsed = this.time.now - this.lastInteractionMs
    this.eventCollector.addDisengagement(this.moduleKey, this.eventCollector.getElapsedMs(), elapsed)
    this.forceAdvance()
  }

  // ── Scene transitions ───────────────────────────────────────────────────────

  protected fadeToScene(key: string): void {
    this.sceneActive = false
    this.inactivityCallTimer?.remove()
    this.inactivityAdvanceTimer?.remove()
    this.buddy?.stopIdle()

    this.cameras.main.fadeOut(300, 224, 244, 255)
    this.cameras.main.once('camerafadeoutcomplete', () => {
      this.scene.start(key)
    })
  }

  // ── Completion celebration ──────────────────────────────────────────────────

  /** Confetti + star particle burst, used when a module completes. */
  protected playCompletionBurst(x: number = CANVAS_WIDTH / 2, y: number = CANVAS_HEIGHT / 2 - 80): void {
    const confettiColors = [0x02c39a, 0xf4a261, 0x065a82, 0xe63946, 0xffb347]

    const dotEmitter = this.add.particles(x, y, 'particle-dot', {
      speed: { min: 150, max: 360 },
      angle: { min: 0, max: 360 },
      scale: { start: 0.9, end: 0 },
      lifespan: 900,
      quantity: 22,
      tint: confettiColors,
      gravityY: 260,
      emitting: false,
    })

    const starEmitter = this.add.particles(x, y, 'particle-star', {
      speed: { min: 100, max: 240 },
      angle: { min: 200, max: 340 },
      scale: { start: 1, end: 0.2 },
      rotate: { start: 0, end: 360 },
      lifespan: 1100,
      quantity: 8,
      tint: [0xffd700, 0xf4a261, 0xffffff],
      gravityY: 160,
      emitting: false,
    })

    dotEmitter.setDepth(200)
    starEmitter.setDepth(200)
    dotEmitter.explode(22)
    starEmitter.explode(8)

    this.time.delayedCall(1300, () => {
      dotEmitter.destroy()
      starEmitter.destroy()
    })
  }

  shutdown(): void {
    this.sceneActive = false
    this.inactivityCallTimer?.remove()
    this.inactivityAdvanceTimer?.remove()
    this.buddy?.destroy()
    this.progressBar?.destroy()
  }
}
